### ISSUE TITLE
2.0 roadmap - server

### ISSUE THREAD

**Issue by rr-** [rr-/szurubooru#83]
- [x] Documentation
- [x] Basic backend structure
    - [x] JSON handling
    - [x] Error handling
    - [x] File uploads
    - [x] Database integration
    - [x] Configuration
    - [x] Authentication
    - [x] ~~Rate limiting~~ let nginx/apache deal with it
- [x] Bumping last login time
- [x] Search engine (subject to change)
- [x] Thumbnail management (`ffmpeg` based)
- [x] Pagination
- [x] Users
    - [x] Creating users
        - [x] Name
        - [x] Email
        - [x] Password
        - [x] Rank
        - [x] Avatar
    - [x] Listing all users
    - [x] Getting single user
    - [x] Editing users
        - [x] Names
        - [x] Password
        - [x] Email
        - [x] Rank
        - [x] Avatar
    - [x] Deleting users
    - [x] Showing email only to currently authenticated user
    - [x] Password reminders
- [x] Posts
    - [x] Creating posts
        - [x] Content
            - [x] Images
            - [x] Animations (detect it's GIF)
            - [x] Flash
            - ~~Youtube~~ dropped after I saw how many youtube videos went down somewhere :expressionless:
            - [x] Image size, file size, content checksum
            - [x] From URL
        - [x] Custom thumbnails
        - [x] Safety
        - [x] Flags (loopable video)
        - [x] Tags
        - [x] Notes
        - [x] Relations
    - [x] Editing posts
        - [x] Content
            - [x] Images
            - [x] Animations (detect it's GIF)
            - [x] Flash
            - ~~Youtube~~ dropped after I saw how many youtube videos went down somewhere :expressionless:
            - [x] Image size, file size, content checksum
            - [x] From URL
        - [x] Custom thumbnails
        - [x] Safety
        - [x] Flags (loopable video)
        - [x] Tags
        - [x] Notes
        - [x] Relations
    - [x] Listing posts - all filters from help apply
    - [x] Viewing single post
    - [x] Deleting posts
    - [x] Rating posts (separate table, keep track of time)
    - [x] Favoriting posts (separate table, keep track of time)
    - [x] Featuring posts (separate table, keep track of time)
    - [x] Keep track of tag usage
    - [x] Snapshots on creating, updating or deleting
    - [x] Output also comments without pagination
    - [x] Output also snapshots without pagination
    - [x] Detect and test missing default tag category when creating new tags - it should create new category behind the scenes, just like it creates new tags
    - ~~Search for duplicates (by hash rather than post contents - maybe download URLs)~~ moved to 2.1
- [x] Comments
    - [x] Creating comments
        - [x] Track comment creation and edit date for use in search
    - [x] Listing comments
    - [x] Viewing single comment
    - [x] Editing comments
    - [x] Deleting comments
    - [x] Rating comments
- [x] Tag categories
    - [x] Listing tag categories
    - [x] Creating tag categories
        - [x] Name
        - [x] Color
    - [x] Editing tag categories
        - [x] Name
        - [x] Color
    - [x] Deleting tag categories
    - [x] Snapshots when creating, updating or deleting
    - [x] Output also snapshots
    - ~~Add some example categories in an upgrade~~ let user do it
- [x] Tags
    - [x] Creating tags
        - [x] Name
        - [x] Implications
        - [x] Suggestions
        - [x] Category
    - [x] Listing tags
    - [x] Viewing single tag
    - [x] Editing tags
        - [x] Name
        - [x] Implications
        - [x] Suggestions
        - [x] Category
    - [x] Deleting tags
    - [x] Exporting `tags.json`
    - [x] Snapshots when creating, updating or deleting
    - [x] Merging tags
    - [x] Tab siblings
    - [x] Output also snapshots
- [x] Snapshots listing
- [x] Global info
    - [x] HDD usage
    - [x] Post count
    - [x] Featured post

**Comment by rr-** [comment]
Day 21, preliminary backend done.
