### ISSUE TITLE
2.0 roadmap - client

### ISSUE THREAD

**Issue by rr-** [rr-/szurubooru#84]
- [x] Bumping last login time
- [x] Top navigation (might be subject to changes)
- [x] Help
- [x] Endless scroll
- [x] Normal scroll
- [x] Reusable file dropper control
- [x] Reusable tagger control
    - [x] Adding new tags
    - [x] Adding implications
    - [x] Removing existing tags
    - [x] Coloring by category
    - [x] Removing duplicates
    - [x] Suggestions and siblings on tag click
- [x] Basic frontend structure
    - [x] Minification of CSS, HTML and JS
    - [x] Templates
    - [x] Controllers
    - [x] Views
    - [x] API
    - [x] Config
    - [x] Authentication
- [x] 404 page
- [x] Users
    - [x] Registration
    - [x] Listing
        - [x] Search input
        - [x] No data to show
    - [x] Viewing
        - [x] Name, registered X ago, last seen X ago, rank
        - [x] Avatar
        - [x] Number of uploads, favorites, posts commented on, liked and disliked posts
        - [x] Resource not found
    - [x] Editing
        - [x] Name
        - [x] Password
        - [x] Email
        - [x] Rank
        - [x] Avatar
        - [x] Deletion
        - [x] Resource not found
    - [x] Browsing settings
    - [x] Password reminders
- [x] Home page
    - [x] Title
    - [x] Number of posts
    - [x] HDD usage
    - [x] Dedicated landing page w/o top nav
    - [x] Featured post
    - [x] Current version
    - [x] Build date
- [x] Posts
    - [x] Listing
        - [x] Search input
        - [x] Safety switching
        - [x] Mass tag
            - [x] Post edited by someone else
        - ~~Hide downvoted posts~~ will implement if asked to
        - [x] No data to show
    - [x] Creating
        - [x] Preview thumbnail
            - [x] Images
            - [x] Videos
            - ~~Flash~~ technically infeasible
            - ~~Youtube~~ dropped
            - [x] URLs
        - [x] Safety
        - [x] Anonymous upload
        - [x] Reorder
        - [x] Remove
    - [x] Editing
        - [x] Content
            - [x] Images
            - [x] Animations (detect it's GIF)
            - [x] Flash
            - [x] Youtube
        - [x] Safety
        - [x] Flags (loopable video)
        - [x] Tags
        - [x] Notes
        - [x] Relations
        - [x] Custom thumbnail
            - [x] From file
            - [x] Discard custom thumbnail
            - ~~Select from image (what about ~~Youtube~~, videos and Flash?...)~~ 2.1
        - [x] Detect it's a duplicate
        - [x] Post edited by someone else
        - [x] Deletion
        - [x] Featuring
        - [x] Resource not found
    - [x] Viewing
        - [x] Search on Google/IQDB
        - [x] Fit modes
        - [x] Post notes
        - [x] Next / previous post
        - [x] Add comment
        - [x] Comments
            - [x] Inline editing
        - [x] Rating
        - [x] Favoriting
        - [x] Resource not found
- [x] Comments
    - [x] Markdown
         - [x] Cross-references (posts, users, tags, searches)
         - [x] Spoilers
         - [x] Small text
         - [x] SJIS/AA
         - [x] Strike-through
    - [x] Listing in dedicated view
        - [x] Endless scroll
        - [x] Normal scroll
        - [x] Inline editing
        - [x] Deletion
        - [x] Rating
        - [x] Page not found?
    - [x] Listing in post view
        - [x] Rating
        - [x] Inline editing
        - [x] Deletion
    - [x] Adding
- [x] Tags
    - [x] Listing
        - [x] Search input
        - [x] No data to show
    - [x] Operations on single tag
        - [x] Showing
        - [x] Editing
        - [x] Deletion
        - [x] Merging
        - [x] Resource not found
    - [x] Tag categories
- [x] Keyboard shortcuts
    - [x] User list
    - [x] Post list
    - [x] Tag list
    - [x] Post view
- [x] History

**Comment by rr-** [comment]
Preview of PoC for post list:

![20160602_234654_pbj](https://cloud.githubusercontent.com/assets/1045476/15762128/5c40787c-291c-11e6-9aa5-860c238d05f2.png)

**Comment by rr-** [comment]
Post view:

![20160608_232417_gun](https://cloud.githubusercontent.com/assets/1045476/15911426/29953c2e-2dd0-11e6-9ea2-825a9b625e0f.png)

Comments are to be implemented later and will be placed below the fold.

**Comment by rr-** [comment]
@kotcrab I've renamed `_fields` to `fields` in the API.

**Comment by kotcrab** [comment]
If you go to `http://szurubooru.local/tag/tag_name/delete` and press `which posts` you will be taken to `http://szurubooru.local/posts/tag_name` which just list all posts. Should probably be `http://szurubooru.local/posts/text=tag_name`.

**Comment by rr-** [comment]
Fixed

**Comment by kotcrab** [comment]
Are you going to implement navigating between posts with active search query? In Szurubooru 1 you could search for something, open post and then view next post that matched search.

**Comment by rr-** [comment]
Not sure if this is necessary, wanted to postpone it till we could test it on https://yume.pl/. The current version respects safety much like other boorus do.

**Comment by kotcrab** [comment]
I know that other boorus doesn't support it, It's pretty awesome feature though.

**Comment by rr-** [comment]
Ok, implemented in e2eee0c

**Comment by kotcrab** [comment]
Wow, that was quick. Thanks a lot.

**Comment by rr-** [comment]
I need mana!

**Comment by rr-** [comment]
Basic post editing is done, but the tag input annoys the hell out of me. I think it needs to be scraped and designed from scratch. :-1:

**Comment by kotcrab** [comment]
Yep, it would be pain to use with more than few tags.

**Comment by rr-** [comment]
@tehoko had the idea to add a single line input that would append to a list below. Each item would have [x] near it.

I think I like the idea for the most part, but following issues remain:

1. How to present suggestions and siblings?
2. What to do about "escaping form", where the more tags you enter, the further the "save" button is?

**Comment by kotcrab** [comment]
How about doing text area where each entered tag becomes a box (could be even colored as tag category), similar to how you can enter multiple emails on Gmail:
![2016-07-17_2155](https://cloud.githubusercontent.com/assets/4594081/16902785/354b90ce-4c69-11e6-8b8a-0ad6f412d542.png)

For suggestions I'd do another section below like "More tags" with wrapping single line of tags. You could click on tag to quickly add it to post tags.

**Comment by tehoko** [comment]
Solution for "save" button moving down:

![image](https://cloud.githubusercontent.com/assets/2924029/16902843/c03446b6-4c6b-11e6-99c2-c7c7018d1503.png)

Entering the edit mode changes the topmost sidebar buttons into "save" and "discard". The current version only has "return" icon, which doesn't really say that everything gets discarded upon clicking. I believe the version suggested above fixes this, while also solving the moving button problem.

As for showing suggestions/siblings, I don't know yet.

**Comment by rr-** [comment]
@kotcrab what you describe is implemented in sz1:

![20160717_222711_tcj](https://cloud.githubusercontent.com/assets/1045476/16902901/a047fee0-4c6d-11e6-97f5-79ea926c4952.png)

And I'm looking for a way to improve this. Example areas for an improvement:

- Related tags disappear after entering another tag, which make relations too ephemeral
- Confirmed tags that contain typos cannot be corrected without retyping from scratch
- No convenient way to remove tag other than last one
- No convenient way to show suggestions and siblings for any tag
- No way to open the tag page to edit its relations
- No way to open the search page to look what's tagged with it
- No visual information regarding tag category

**Comment by rr-** [comment]
BTW most probably we'll simplify upload form:

1. Arrange the upload into tabular / grid layout.
2. Restrict user input to choice of safety for each post, and manipulating the list (order, remove, add).
3. Add `default_tag` to `config.yml` (equal by default to `tagme`). This tag will be used when user hits the 'submit' button.

Any fine tuning to the posts will then be accomplished via the edit form: tags, thumbnail, notes, etc.

The reason behind this decision came after considering all the odds:

1.  This simplifies uploading process to the extreme, promoting fast content uploading and site growth.
2. This allows the users to keep the "to upload" queue size in check.
3. This sort of behavior is further reinforced by autotagger. In case of yume.pl, we have a success ratio at about 21%. That's a lot of time saved.
4. Remaining development costs are cut in half (if you count out history/snapshots which requires redesigning).
5. Mass tag is given more highlight.

Possible critique and rebuttals in advance:

1. *This leads to users neglecting tagging altogether.*  
IMO short editing sessions when users / mods are full of energy are better than letting upload queues rot on disk for weeks/months. Even if this leads to the same lazy behavior pattern, at least the content will be seen by the users rather than withering away.
2. *This requires the API clients to upload posts in 2 step process.*  
False. It's not like the upload API changes in any way - the external clients will be able to manipulate everything during upload like they always could.
3. *Too much new content leads to quality degradation.*  
This has to be yet assessed.
4. *This is bad in terms of UX.*  
All of the mocks of the upload form where we tried to combine batch uploads with the ability to control every aspect of the post like in the edit form, looked / behaved bad in some aspect. In contrast, I don't think it makes such a difference to quickly choose safety for a post, and then proceed to edit its details after 2 clicks. Same goes for batch sessions, for which &lsaquo; &rsaquo; buttons will be of great help.

**Comment by rr-** [comment]
@kotcrab I changed the API a little - clients need to send `version` when updating (`PUT`) and deleting (`DELETE`) resources. This is to prevent problems with concurrent editing.

**Comment by kotcrab** [comment]
@rr- Ok, I updated auto tagger, sorry for the delay.

**Comment by rr-** [comment]
No worries, I'm just pinging you FYI so you don't get mad when things break
